version: '2.4' # ver 3 does not support runtime.
services:
##########
  perforce:
    image: perforce
    build:
      context: .
      dockerfile: perforce.dockerfile
    dns:
      - 10.19.185.252
      - 10.19.185.253
    dns_search:
      - nvidia.com
    env_file:
      - vulcan.env
      - p4config.env
    volumes:
      - perforce:/p4
    tmpfs:
      - /run
      - /tmp
      - /home/devel/.vulcan
    stdin_open: true
    tty: true
    network_mode: "host"
##########
  dvsbuild:
    image: dvsbuild
    build:
      context: .
      dockerfile: dvsbuild.dockerfile
    environment:
      - LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
    env_file:
      - vulcan.env
    volumes:
      - perforce:/p4
    tmpfs:
      - /run
      - /tmp
    stdin_open: true
    tty: true
    network_mode: "host"
#
  dvstest:
    runtime: nvidia
    image: dvstest
    build:
      context: .
      dockerfile: dvstest.dockerfile
    volumes:
      - perforce:/p4
    tmpfs:
      - /run
      - /tmp
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    stdin_open: true
    tty: true
    network_mode: "host"
#
volumes:
  perforce:
    external: true
# EOF
