version: '2.4' # ver 3 does not support runtime.
services:
##########
  dvsbuild:
    image: dvsbuild
    build:
      context: .
      dockerfile: dockerfile.dvsbuild
    environment:
      - LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
    env_file:
      - vulcan.env
      - p4config.env
    volumes:
      - perforce:/p4
    tmpfs:
      - /run
      - /tmp
      - /home/devel/.vulcan
    command: "python3 -m jupyterlab --no-browser --ip 0.0.0.0"
    expose:
      - "8888"
    ports:
      - "8888"
##########
  dvstest:
    runtime: nvidia
    image: dvstest
    build:
      context: .
      dockerfile: dockerfile.dvstest
    volumes:
      - perforce:/p4
    tmpfs:
      - /run
      - /tmp
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    stdin_open: true
    tty: true
#
volumes:
  perforce:
    external: true
# EOF
