version: '2.4' # ver 3 does not support nvidia runtime.

volumes:
  julia:
  perforce:
    external: true

services:
  julia:
    image: eordian/julia-cuda
    build: .
    runtime: nvidia
    # uncomment dns, if using VPN.
    # dns:
    #   - 10.19.185.252
    #   - 10.19.185.253
    # dns_search:
    #   - nvidia.com
    environment:
      - NODE_MIRROR=https://mirrors.huaweicloud.com/nodejs/
    ##### enable it after jupyterlab has been installed.
    command: "bash -c \"cd / ; /home/devel/.julia/conda/3/bin/jupyter lab --ip 0.0.0.0 --no-browser\""
    ##### init
    # command: "julia --load /tmp/julia-cuda/init.jl"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - julia:/home/devel/
      - perforce:/p4:ro
      - .:/tmp/julia-cuda/:ro
    network_mode: bridge
    expose:
      - 8888
