version: '2.4' # ver 3 does not support nvidia runtime.

volumes:
  julia:
  perforce:
    external: true

services:
  julia:
    image: eordian/julia-cuda
    build: .
    mem_limit: 30G
    runtime: nvidia
    expose:
      - "22"
      - "8888"
    # uncomment dns, if using VPN.
    # dns:
    #   - 10.19.185.252
    #   - 10.19.185.253
    # dns_search:
    #   - nvidia.com
    network_mode: "host"
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/devel/.julia/conda/3/bin/
      - NODE_MIRROR=https://mirrors.huaweicloud.com/nodejs/
    ##### enable it after jupyterlab has been installed.
    command: "bash -c \"cd / ; /home/devel/.julia/conda/3/bin/jupyter lab --ip 0.0.0.0 --no-browser\""
    ##### init
    # command: "julia --load /tmp/julia-cuda/init.jl"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - julia:/home/devel/
      - perforce:/p4:ro
      - .:/tmp/julia-cuda/:ro
# networks:
#   default:
#     ipam:
#       driver: default
#       config:
#         - subnet: "192.168.11.0/24"
