version: '2.4' # ver 3 does not support nvidia runtime.

volumes:
  julia:
  perforce:
    external: true

services:
  julia:
    image: eordian/julia-cuda
    build: .
    runtime: nvidia
    expose:
      - "22"
      - "8888"
    # uncomment dns & network_mode, comment ports, if using VPN.
    network_mode: "host"
    dns:
      - 10.19.185.252
      - 10.19.185.253
    dns_search:
      - nvidia.com
    # ports:
    #   - "0.0.0.0:3022:22"
    #   - "0.0.0.0:3888:8888"
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/devel/.julia/conda/3/bin/
      - NODE_MIRROR=https://mirrors.huaweicloud.com/nodejs/
      # - NODE_MIRROR=https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/
    # restart: always
    stdin_open: true
    tty: true
    ##### enable it after jupyterlab has been installed.
    command: "bash -c \"cd / ; /home/devel/.julia/conda/3/bin/jupyter lab --ip 0.0.0.0 --no-browser\""
    ##### init command
    # command: "julia -i --load /tmp/dockerfiles/init.jl"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - julia:/home/devel/
      - perforce:/p4:ro
      - .:/tmp/dockerfiles:ro
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "192.168.11.0/24"
