version: "3"

services:
  jupyter:
    image: eordian/datascience-notebook
    build: .
    ports:
      - "8888"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /scratch:/scratch
    working_dir: /
