version: "3"

services:
  jupyter:
    image: jupyter/datascience-notebook
    environment:
      - NODE_MIRROR=https://mirrors.huaweicloud.com/nodejs/
      - PIP_USE_MIRRORS=true
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /scratch:/scratch
      - perforce:/p4
    working_dir: /
volumes:
  perforce:
    external: true
