version: '2.4' # ver 3 does not support runtime.
services:
##########
  dvsbuild:
    image: eordian/dvsbuild
    build:
      context: .
    runtime: nvidia
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    env_file:
      - env.txt
    working_dir: /
    volumes:
      - work:/home/jovyan/work
      - perforce:/p4
    tmpfs:
      - /run
      - /tmp
      - /home/jovyan/.vulcan
    ports:
      - "8888"
#
volumes:
  work:
  perforce:
    external: true
#
