# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - /p4/postgres:/var/lib/postgresql/data
      - /p4:/p4
      - /scratch:/scratch
    tmpfs:
      - /run
      - /tmp
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
